name: Stock Price Update
on:
  schedule:
    - cron: '0 * * * *'   # 매 시간 정각(UTC)마다 자동 실행   
  workflow_dispatch:  # 깃허브 웹에서 수동으로 버튼 눌러 실행!


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # v3에서 v4로 최신 업데이트 완료!

      - name: Set up Python
        uses: actions/setup-python@v5  # v4에서 v5로 최신 업데이트 완료!
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install yfinance requests

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python stock_bot.py  # 띄어쓰기 없는 새로운 이름으로 수정!
